#!/bin/bash

# This file is part of ka_GE.spell
# Copyright (C) 2016 Gabriel Margiani
#
#  is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
#  is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ka_GE.spell  If not, see <http://www.gnu.org/licenses/>.

cd $(dirname $0)/build

if [[ $1 == "--help" ]] || [[ $1 == "-h" ]]; then
	echo "Creates a hunspell dict using Bumbeishvilis wordlist from mysql.";
	exit
fi

if [[ ! -f ../dbaccess ]]; then
	echo "Create a file called 'dbaccess' containing"
	echo "DBUSER=..."
	echo "DBNAME=..."
	echo "DBPASS=..."
	echo "so I access the database."
	exit 1;
fi

source ../dbaccess

LICENSE="
	# This file was generated by ka_GE.spell script by Gabriel Margiani using a
	# Georgian wordlist by Dato Bumbeishvili
	# (https://github.com/bumbeishvili/GeoWordsDatabase)
"
echo "Reading word list from db"
mysql -NL "-u$DBUSER" "-p$DBPASS" "$DBNAME" -e "SELECT word_geo FROM words ORDER BY word_geo;" | uniq >ka_GE.words

echo "Preparing dictionary"
#echo "# $LICENSE" >ka_GE.dic # fails in munch
wc -l <ka_GE.words >ka_GE.tmp
cat ka_GE.words >>ka_GE.tmp

echo "Creating affix file"
echo "$LICENSE" >ka_GE.aff
echo "SET UTF-8" >>ka_GE.aff

echo "Create TRY character list:"
TRY=$(mysql -NL "-u$DBUSER" "-p$DBPASS" "$DBNAME" -e "SELECT title FROM statistics WHERE loadKey='GeoCharsCount' ORDER BY quantity DESC;" | tr -d "\n")
echo $TRY;
echo "TRY $TRY" >>ka_GE.aff

echo "Append affix list"
cat ../affixes >>ka_GE.aff

echo "Munch dictionary"
munch ka_GE.tmp ka_GE.aff>ka_GE.dic

echo "Done."
